// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ChangeTheme: typeof import('./src/components/ChangeTheme.vue')['default']
    CodePen: typeof import('./src/components/CodePen.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    PostWrapper: typeof import('./src/components/PostWrapper.vue')['default']
  }
}

export { }
